//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppTEST.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ARSCAN", Namespace="http://schemas.datacontract.org/2004/07/ScanPmrService.Models")]
    [System.SerializableAttribute()]
    public partial class ARSCAN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODE_BARField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODE_OPE_SCANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] IMMAGINE_FRONTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] IMMAGINE_RETROField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODE_BAR {
            get {
                return this.CODE_BARField;
            }
            set {
                if ((object.ReferenceEquals(this.CODE_BARField, value) != true)) {
                    this.CODE_BARField = value;
                    this.RaisePropertyChanged("CODE_BAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODE_OPE_SCAN {
            get {
                return this.CODE_OPE_SCANField;
            }
            set {
                if ((object.ReferenceEquals(this.CODE_OPE_SCANField, value) != true)) {
                    this.CODE_OPE_SCANField = value;
                    this.RaisePropertyChanged("CODE_OPE_SCAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] IMMAGINE_FRONTE {
            get {
                return this.IMMAGINE_FRONTEField;
            }
            set {
                if ((object.ReferenceEquals(this.IMMAGINE_FRONTEField, value) != true)) {
                    this.IMMAGINE_FRONTEField = value;
                    this.RaisePropertyChanged("IMMAGINE_FRONTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] IMMAGINE_RETRO {
            get {
                return this.IMMAGINE_RETROField;
            }
            set {
                if ((object.ReferenceEquals(this.IMMAGINE_RETROField, value) != true)) {
                    this.IMMAGINE_RETROField = value;
                    this.RaisePropertyChanged("IMMAGINE_RETRO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IScanPmrService")]
    public interface IScanPmrService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanPmrService/ValidationBarCodes", ReplyAction="http://tempuri.org/IScanPmrService/ValidationBarCodesResponse")]
        string ValidationBarCodes(string barCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanPmrService/ValidationBarCodes", ReplyAction="http://tempuri.org/IScanPmrService/ValidationBarCodesResponse")]
        System.Threading.Tasks.Task<string> ValidationBarCodesAsync(string barCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanPmrService/InsertPmr", ReplyAction="http://tempuri.org/IScanPmrService/InsertPmrResponse")]
        string InsertPmr(ConsoleAppTEST.ServiceReference1.ARSCAN input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScanPmrService/InsertPmr", ReplyAction="http://tempuri.org/IScanPmrService/InsertPmrResponse")]
        System.Threading.Tasks.Task<string> InsertPmrAsync(ConsoleAppTEST.ServiceReference1.ARSCAN input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScanPmrServiceChannel : ConsoleAppTEST.ServiceReference1.IScanPmrService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScanPmrServiceClient : System.ServiceModel.ClientBase<ConsoleAppTEST.ServiceReference1.IScanPmrService>, ConsoleAppTEST.ServiceReference1.IScanPmrService {
        
        public ScanPmrServiceClient() {
        }
        
        public ScanPmrServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScanPmrServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScanPmrServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScanPmrServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ValidationBarCodes(string barCodes) {
            return base.Channel.ValidationBarCodes(barCodes);
        }
        
        public System.Threading.Tasks.Task<string> ValidationBarCodesAsync(string barCodes) {
            return base.Channel.ValidationBarCodesAsync(barCodes);
        }
        
        public string InsertPmr(ConsoleAppTEST.ServiceReference1.ARSCAN input) {
            return base.Channel.InsertPmr(input);
        }
        
        public System.Threading.Tasks.Task<string> InsertPmrAsync(ConsoleAppTEST.ServiceReference1.ARSCAN input) {
            return base.Channel.InsertPmrAsync(input);
        }
    }
}
